제품 POST뷰 완료 및 동작테스트 확인
wecode-bootcamp-korea/15-1st-LineAmigos-backend pull request #2
Opened 2020-12-18 06:48 UTC by Muntari29

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
전체 Product 뷰 중 POST뷰 구현 완료 및 동작테스트 확인
		 
## 수정 사항들 자세한 내용
product/views.py 작성
product/urls.py 작성

## 기타 질문 및 특이 사항
추가로 validation해야할 사항은 없는것으로 확인하였는데 의견 부탁드립니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-18 07:42 UTC, jamessoun93 commented
`.DS_Store` 파일들, `csv` 파일들, `db_uploader` <- 이런 파일들은 `git` 에 올라오면 안되는 파일들입니다. 없애주시고 `gitignore` 에도 추가해주세요.

2020-12-20 14:08 UTC, jamessoun93 requested changes
- `.DS_Store` 도 `gitignore` 에 추가해주세요.
- `.gitignore` 에 추가하셨어도 이미 `git` 에 `push` 한 파일들은 없어지지 않습니다. 이미 `push` 한 파일들을 지우는법에 대해 알아보시고 적용해주세요.

2020-12-20 14:08 UTC, jamessoun93 commented on product/views.py
> +                raise KeyError
이 부분은 남겨놓으신 주석과 `raise` 하시는 에러를 보면 `KeyError` 를 잡는 코드같은데 `if` 문의 조건은 위에서 이미 찾아서 변수에 담은 값들의 `value` 들이 빈 문자열인지를 체크하는 것 같네요.

어떤 의도로 작성하신건가요?

2020-12-20 14:08 UTC, jamessoun93 commented on product/views.py
> +            return JsonResponse({'MESSAGE' : 'EXIST_PRODUCT'}, status=401)
해당 조건에 일치하는 제품이 없을 때 어떻게할지를 `if` 문안에 넣는것 보다 반대로 꺼내주는게 더 좋아보이네요. 
그리고 `401`은 `UNAUTHORIZED` 의 의미로 사용되는 `status code` 입니다. 수정해주세요.

2020-12-20 14:08 UTC, jamessoun93 commented on product/views.py
> +class ProductView(View):
해당 View 클래스가 리스트를 뿌려주는지 어떤 특정 제품에 대한 상세정보를 뿌려주는지 코드를 봐야만 알 수 있습니다. 클래스명을 더 명확하게 지어주세요.

2020-12-20 14:08 UTC, jamessoun93 commented on product/views.py
> +            products = Product.objects.select_related('category', 'category__menu').prefetch_related('image_set').all()
여기서 `select_related` 와 `prefetch_related` 를 사용하신 이유와 둘의 차이를 답글로 설명해주세요.

2020-12-20 14:08 UTC, jamessoun93 commented on product/views.py
> +            return JsonResponse({'MESSAGE' : 'NO_PRODUCT'}, status=500)
현재 코드에서 `DoesNotExist` 에러가 발생할 수 있을까요?

2020-12-20 14:08 UTC, jamessoun93 commented on product/views.py
> +            return JsonResponse({'product_id' :product_detail}, status=200)
`key` 와 `value` 가 매칭이 안됩니다. 프론트와 상의 후 수정해주세요.

2020-12-20 14:08 UTC, jamessoun93 commented on product/views.py
> +            return JsonResponse({'MESSAGE' : 'SUCCESS'}, status=400)
뭔가 마무리가 덜 된 코드같네요. 수정해주세요.

2020-12-21 01:43 UTC, Muntari29 commented on product/views.py
> +                raise KeyError
admin 입장에서 제품을 등록할때 위의 4가지는 필수 입력값으로 지정하였습니다.
만약 admin 입장에서 제품을 등록하고자할때 이미지 값이 없다면 image='' 오는지 아예 Imagr 키워드가 주어지지 않는지를 자세히 모른상태에서 위 2가지 경우를 모두 고려하여 "NOT_ENOUGH_INFO"를 반환하도록 구성해보았습니다.

2020-12-21 01:51 UTC, Muntari29 commented on product/views.py
> +            return JsonResponse({'MESSAGE' : 'EXIST_PRODUCT'}, status=401)
수정하겠습니다!

2020-12-21 01:52 UTC, Muntari29 commented on product/views.py
> +class ProductView(View):
모든 제품 정보를 뿌려주는 뷰로 클래스명 수정하겠습니다

2020-12-21 01:59 UTC, Muntari29 commented on product/views.py
> +            products = Product.objects.select_related('category', 'category__menu').prefetch_related('image_set').all()
menu      = category의 정참조
category = product의 정참조
image      = product의 역참조
위와 같은 모델링 구성으로 product에서 menu에 대한 쿼리를 가져올 수 없었습니다.
select_related = OTO, OTM, 정참조 관계에서 사용하며
prefetch_related = select_related를 포관하며 MTM 및 역참조 관계에서 사용할 수 있습니다.

여기서 이 두가지를 함께 사용한 이유는 불필효한 쿼리를 줄이기 위함이며
쿼리를 줄이는 측면에서는 select_related가 더 효율적인것으로 알고 있습니다.

따라서 product DB에 1번 접근하여 카테고리 속성값, 메뉴 속성값, 이미지 속성값을 읽어와 사용할 수 있도록 함께  구성하였습니다.

2020-12-21 02:03 UTC, Muntari29 commented on product/views.py
> +            return JsonResponse({'MESSAGE' : 'NO_PRODUCT'}, status=500)
사실 발생할 수 없는 에러입니다.
프로젝트 진행간 반드시 product DB내에는 정보가 반드시 있기 때문입니다.
허나 예기치 못한 상황으로 product DB가 다 날아갈수도 있지 않을까? 하는 내용으로 작성하였습니다.
결론적으로 불필요한 코드로 생각하여! 삭제하도록 하겠습니다.

2020-12-21 02:07 UTC, Muntari29 commented on product/views.py
> +            return JsonResponse({'product_id' :product_detail}, status=200)
product_id -> product로 수정하기로 하였습니다.

2020-12-21 02:19 UTC, Muntari29 commented on product/views.py
> +            return JsonResponse({'MESSAGE' : 'SUCCESS'}, status=400)
수정하겠습니다!

2020-12-21 04:42 UTC, jamessoun93 commented on product/views.py
> +                raise KeyError
설명 감사합니다. 이럴때는 더욱 더 명확하게 구분해주시는게 좋아보입니다. 빈 스트링인지 파악하는것은 KeyError 에 해당하지 않습니다. 따라서 빈 스트링의 경우 ValueError를 잡아줄 수 있게끔 변경해주세요.

2020-12-21 04:55 UTC, jamessoun93 requested changes

2020-12-21 04:55 UTC, jamessoun93 commented on product/views.py
> +            return JsonResponse({'MESSAGE' : 'NO_PRODUCT'}, status=500)
네 의도는 알겠으나 product 데이터가 하나도 존재하지 않더라도 발생할 수 없는 에러입니다. QuerySet 은 비었으면 빈 리스트를 반환하기 때문이죠!

2020-12-21 04:55 UTC, jamessoun93 commented on product/views.py
> +            products = Product.objects.select_related('category', 'category__menu').prefetch_related('image_set').all()
설명 잘해주셨네요 👍  

하지만 select_related와 prefetch_related 는 불필요한 쿼리를 줄이기 위함이지 정참조, 역참조 관계에서 가져올 수 없는 값을 가져오게 해주는 메소드는 아닙니다. 지금 구현중인 기능 같은경우 이 두 메소드가 없어도 정상적으로 작동해야합니다. 

`select_related` 와 `prefetch_related` 의 차이는 정참조, 역참조의 차이도 있지만 실제 `JOIN` 을 어디서 하냐의 차이가 있습니다. `select_related` 같은경우 데이터베이스에서 `JOIN` 을 한 채로 가져오고, `prefetch` 는 가져와서 `Python` 으로 `JOIN` 을 하게 됩니다. 이런 차이들을 확인하려면 기본적으로 데이터가 많아아하므로 지금 단계에서는 아직 비중을 많이 두실 필요는 없습니다.

2020-12-21 05:06 UTC, Muntari29 commented on product/views.py
> +                raise KeyError
감사합니다 수정하겠습니다.

2020-12-21 05:07 UTC, Muntari29 commented on product/views.py
> +            return JsonResponse({'MESSAGE' : 'NO_PRODUCT'}, status=500)
빈 리스트를 반환해주는것은 기술블로그에 작성하여 숙지하도록 하겠습니다. 감사합니다

2020-12-21 07:46 UTC, Muntari29 commented on product/views.py
> +            products = Product.objects.select_related('category', 'category__menu').prefetch_related('image_set').all()
감사합니다! 모두 select 와 prefetch를 쓰지않아도 잘 동작합니다!

2020-12-21 07:57 UTC, Muntari29 commented on product/views.py
> +            return JsonResponse({'MESSAGE' : 'NO_PRODUCT'}, status=500)
따라서 삭제해야할 부분과 삭제하지 않아야할부분으로 나누었으며 해당 코드는 삭제처리하였습니다.

2020-12-21 11:47 UTC, jamessoun93 commented
LGTM 👍

2020-12-21 11:47 UTC, merged