회원가입/로그인1차
wecode-bootcamp-korea/15-1st-LineAmigos-backend pull request #3
Opened 2020-12-19 09:17 UTC by petersoh414

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
회원가입 / 로그인 구현 하였습니다! 암호화/ 토큰 발급까지 구현하였고, 데코레이터를 추가 구현할 예정입니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-20 14:24 UTC, jamessoun93 requested changes

2020-12-20 14:24 UTC, jamessoun93 commented on user/utils.py
> +            return JsonResponse({'message': "EXPIRED_TOKEN"}, status = 401)
이 에러는 언제 raise 되는지와 지금 작성하신 코드에서 이 에러가 잡히는지 확인해보셨을까요?

2020-12-20 14:24 UTC, jamessoun93 commented on user/views.py
> +from .utils  import SignInConfirm
```suggestion
import json, re, bcrypt, jwt

from django.http            import JsonResponse
from django.views           import View
from django.core.exceptions import ObjectDoesNotExist, ValidationError

from lineamigos.settings import SECRET_KEY, ALGORITHM

from .models import User, PhoneNumber, Gender
from .utils  import SignInConfirm
```
이런식으로 import 문이 많을 경우 분류해서 나눠주시면 가독성이 좋아집니다.

2020-12-20 14:24 UTC, jamessoun93 commented on user/views.py
> +    return re.match(phone_number_regex, phone_number)
이런것들은 따로 파일로 분리해서 import 해서 사용해주세요.

2020-12-20 14:24 UTC, jamessoun93 commented on user/views.py
> +            phone_number    = data.get("phone_number")
여기서 `.get()`을 쓰신 이유를 코멘트로 설명해주세요.

2020-12-20 14:24 UTC, jamessoun93 commented on user/views.py
> +            print(data)
개발단계 확인용 print 문 사용 흔적이 있어서 기분이 좋네요 👍  하지만 git 에 push 해주실때는 print문들은 없애주세요~

2020-12-20 14:24 UTC, jamessoun93 commented on user/views.py
> +                return JsonResponse({'message': 'INVALID_PHONE_NUMBER_FORMAT'}, status=400)
전부 인증오류니까 `UNAUTHORIZED`를 뜻하는 `401`을 띄워주시는게 더 적합합니다.

2020-12-20 14:24 UTC, jamessoun93 commented on user/views.py
> +            gender_id = Gender.objects.get(name=data['gender']).id
`data['password']` 와 `data['gender']` 는 위에서 변수에 이미 꺼내서 저장하셔서 해당 변수로 사용하시면 되겠네요.

2020-12-20 14:24 UTC, jamessoun93 commented on user/views.py
> +            print(phone_number_id)
여기 print문도 마찬가지입니다.

2020-12-20 14:24 UTC, jamessoun93 commented on user/views.py
> +                phone_number=data["phone_number"]).id
- 여기 `data["phone_number"]` 도 마찬가지입니다.
- 그리고 따옴표는 파일 전체적으로 통일시켜주세요.

2020-12-20 14:24 UTC, jamessoun93 commented on user/views.py
> +                phone_number_id=phone_number_id
`=`을 기준으로 정렬해주세요.

2020-12-20 14:24 UTC, jamessoun93 commented on user/views.py
> +                return JsonResponse({'message': 'USER_NOT_FOUND'}, status=401)
이렇게 여러단계로 nesting 해줄 필요없이 첫번째 `if` 문 조건을 반대로 바꾸면 `else` 문도 필요없어지고 조금 더 깔끔해질 수 있을 것 같네요. 한번 시도해보세요!

2020-12-20 14:25 UTC, jamessoun93 commented
리뷰 반영해주시고 승희님과 함께 `.DS_Store` 파일들 전부 없애주세요.

2020-12-21 01:42 UTC, petersoh414 commented on user/views.py
> +                phone_number_id=phone_number_id
반영해서 수정했습니다!

2020-12-21 01:42 UTC, petersoh414 commented on user/views.py
> +            print(phone_number_id)
반영해서 수정했습니다!

2020-12-21 01:42 UTC, petersoh414 commented on user/views.py
> +            print(data)
말씀하신대로 수정했습니다!

2020-12-21 01:44 UTC, petersoh414 commented on user/views.py
> +    return re.match(phone_number_regex, phone_number)
utils.py에 함수들은 옮겼서 import하도록 수정했습니다! 
근데 `username_regex` 와 같은 변수들도 utils.py에 옮겨놓고 불러와서 같이 사용이 가능한가요? 그 부분이 불 명확해서, 각각의 regex변수들은 일단 남겨두었습니다!

2020-12-21 01:44 UTC, petersoh414 commented on user/views.py
> +from .utils  import SignInConfirm
리뷰해주신 부분 반영해서 수정했습니다!

2020-12-21 01:46 UTC, petersoh414 commented on user/utils.py
> +            return JsonResponse({'message': "EXPIRED_TOKEN"}, status = 401)
제가 이해하기론 인증 시간이 만료 되었을 때 발생하는 것으로 알고 있습니다! 에러가 잡히는걸 확인하진 못했지만, 필요한 설정이라고 생각해서 넣어두었습니다!

2020-12-21 01:47 UTC, petersoh414 commented on user/views.py
> +                return JsonResponse({'message': 'INVALID_PHONE_NUMBER_FORMAT'}, status=400)
수정 했습니다!

2020-12-21 02:56 UTC, petersoh414 commented on user/views.py
> +            gender_id = Gender.objects.get(name=data['gender']).id
반영해서 수정했습니다!

2020-12-21 02:57 UTC, petersoh414 commented on user/views.py
> +                phone_number=data["phone_number"]).id
반영해서 수정했습니다!

2020-12-21 03:48 UTC, petersoh414 commented on user/views.py
> +                return JsonResponse({'message': 'USER_NOT_FOUND'}, status=401)
의도하신 방향이 맞는지 확신이 서진 않는데, 일단 수정해서 푸쉬해봅니다! 확인하고 알려주세요!

2020-12-21 04:03 UTC, petersoh414 commented on user/views.py
> +            phone_number    = data.get("phone_number")
`.get()`을 사용한 특별한 이유는 없습니다. 저희가 받아오는 json데이터의 value값을 저장하는 것으로만 알고 있습니다!
 `data['']`로 저장하는 것도 가능한 것으로 알고 있습니다. 이 둘의 근본적인 차이점은 잘 모르겠습니다!

코멘트와는 별개로, 제가 처음에 gender_id와 phone_number_id 도 json data에 포함되있다고 착각했던 부분이 있어, 이 부분은 삭제 했습니다!

2020-12-21 04:58 UTC, jamessoun93 commented on user/utils.py
> +            return JsonResponse({'message': "EXPIRED_TOKEN"}, status = 401)
정확합니다! 하지만 지금 저희는 jwt 에 유효기간 설정을 해주지 않고 있기때문에 발생할 일이 없는 에러겠죠?

2020-12-21 05:06 UTC, jamessoun93 requested changes

2020-12-21 05:06 UTC, jamessoun93 commented on user/views.py
> +            else:
위의 if 조건에 맞지 않다면 바로 내려오게되고, if 조건에 걸린다면 return 문이 있어서 함수가 종료되니 else 는 불필요합니다.

2020-12-21 05:06 UTC, jamessoun93 commented on user/views.py
> +                return JsonResponse({'message': 'USER_NOT_FOUND'}, status=401)
- username 변수에 user 객체를 저장해주고 계신데 변수명과 싱크가 맞지 않으니 수정해주세요.
- 그리고 아래 username 부분에서 get() 으로 유저 객체를 가져오고 계신데 존재하지 않는다면 에러가 발생하게 됩니다. 따라서 if 문이 통째로 불필요하게 되는거죠. 이런 경우 어떤 에러를 잡아줘야하는지 확인해서 추가해주세요.

2020-12-21 05:06 UTC, jamessoun93 commented on user/views.py
> +            phone_number  = data.get("phone_number")
`data.get('username')` 과 `data['username']` 의 차이를 꼭 알고 사용해주셔야 합니다. 한번 알아보시고 코멘트로 둘의 차이를 설명해주시고 어려우시다면 제게 말씀해주세요.

2020-12-21 06:41 UTC, petersoh414 commented on user/views.py
> +            phone_number  = data.get("phone_number")
제가 막연하게 알기론 key가 존재할 때 리턴해주는 값 자체는 동일하지만, 장고에서는 `username` 이라는 `key` 값이 data안에 없을 때 `data[`username]`은 `keyError`를 반환해주는 반면, `data.get('username')은 `None`을 반환해주어 `dictionary`에 해당 키 값의 존재유무를 에러로 인식하지 않는것 같습니다(?!)

2020-12-21 06:53 UTC, petersoh414 commented on user/utils.py
> +            return JsonResponse({'message': "EXPIRED_TOKEN"}, status = 401)
넵! 일단 이 부분은 제거하겠습니다! 프로젝트랑 상관없이 개인적으로 구현해보고 질문사항있으면 차후에 여쭤보겠습니다!

2020-12-21 07:48 UTC, petersoh414 commented on user/views.py
> +                return JsonResponse({'message': 'USER_NOT_FOUND'}, status=401)
Object.DoesNotExist 가 아닐까 싶어서, except 구문에 User.DoesNotExist: 를 추가하고, 리턴 메시지를 옮겼습니다!

2020-12-21 07:48 UTC, petersoh414 commented on user/views.py
> +                return JsonResponse({'message': 'USER_NOT_FOUND'}, status=401)
username -> user 로 수정하고
Object.DoesNotExist 가 아닐까 싶어서, except 구문에 User.DoesNotExist: 를 추가하고, 리턴 메시지를 옮겼습니다!

2020-12-21 10:22 UTC, petersoh414 commented on user/utils.py
> +            return JsonResponse({'message': "EXPIRED_TOKEN"}, status = 401)
user/views.py 에 encoding 과정에서 유효시간을 추가로 설정해주었습니다! 시간이 정상적으로 작동하는지는 확인은  못했습니다만, 로직상으로 문제가 없는지 질문 드립니다!

2020-12-21 10:28 UTC, petersoh414 commented on user/views.py
> +            else:
처음에 말씀셨던 부분으로 돌아가서, 조금 효율적으로 생각할 때, 결국 처음에 동일한 username을 찾지 못하면,  

except 구문에`User.DoesNotExist`로 잡아줄수 있지 않을까 싶어 수정했습니다.

그릭고 위에 부분도 password가 동일하지 않을 경우엔 에러처리하고, 그렇지 않다면 암호화 과정에서 토큰 발급하며 2시간동안의 유효 시간을 추가했습니다!

2020-12-21 10:29 UTC, petersoh414 commented on user/views.py
> +            phone_number  = data.get("phone_number")
따라서, 위의 값들이 하나라도 존재하지 않으면 `Key Errror` 처리 하기위해서, `date['username']` 형태로 수정하였습니다

2020-12-21 13:32 UTC, jamessoun93 commented on user/views.py
> +            phone_number  = data.get("phone_number")
정확합니다!! 👍👍👍

2020-12-21 13:34 UTC, jamessoun93 commented on user/views.py
> +            payload      = {'username': user.id, 'exp': datetime.now() +timedelta(hours=2)}
👍👍👍

2020-12-21 13:34 UTC, jamessoun93 commented on user/views.py
> +            else:
확인했습니다 👍

2020-12-21 13:34 UTC, jamessoun93 commented on user/views.py
> +                return JsonResponse({'message': 'USER_NOT_FOUND'}, status=401)
확인했습니다 👍

2020-12-21 13:34 UTC, jamessoun93 commented on user/views.py
> +                return JsonResponse({'message': 'USER_NOT_FOUND'}, status=401)
확인했습니다 👍

2020-12-21 13:34 UTC, jamessoun93 approved these changes
LGTM 👍

2020-12-21 13:35 UTC, merged