[Product_Add] RESTfulAPI 최신순 정렬 및 search 기능 구현완료
wecode-bootcamp-korea/15-1st-LineAmigos-backend pull request #5
Opened 2020-12-22 07:57 UTC by Muntari29

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
Product 추가 기능 구현 / restfulapi 적용 및 테스트 완료

## 수정 사항들 자세한 내용
product/views.py 수정

## 기타 질문 및 특이 사항
RESTfulAPI 구현하는 것을 목표로 하였습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-22 08:04 UTC, Muntari29 commented on product/views.py
> +        products = Product.objects.all().order_by('-id')if ordering else Product.objects.all()
삼항 연산자를 전용하였는데 올바른 방법인지 궁금합니다.

2020-12-22 15:00 UTC, lordmyshepherd requested changes

2020-12-22 15:00 UTC, lordmyshepherd commented on image 복사본.csv
> -상품명, 가격, 이미지, 카테고리
csv 파일은 github에 올라오지 않도록 .gitignore에 추가해주세요!

2020-12-22 15:00 UTC, lordmyshepherd commented on product/views.py
> +            products = Product.objects.all()
```suggestion

```

2020-12-22 15:00 UTC, lordmyshepherd commented on product/views.py
> +
`sort`와 `ordering`이 같이 들어오는 경우는 어떻게 되나요?

2020-12-22 15:00 UTC, lordmyshepherd commented on product/views.py
> +            product_id = int(request.GET.get('product', 1))
Restful API를 구현할 때, `id = 1`인  product를 불러와야 하는 경우 `path parameter`를 사용해서 구현해 주셔야 합니다.
```suggestion
    def get(self, request, product_id):

```

2020-12-23 01:16 UTC, Muntari29 commented on image 복사본.csv
> -상품명, 가격, 이미지, 카테고리
![image](https://user-images.githubusercontent.com/65607601/102947900-ca891080-4507-11eb-8b93-a17c6fa29f9b.png)
혹식 csv파일명에 한글이 포함되서 이런문제가 있는걸까요?
원격저장소 삭제하는 명령어로도 삭제를 할 수 없습니다.
의견 부탁드립니다!

2020-12-23 01:26 UTC, Muntari29 commented on product/views.py
> +            products = Product.objects.all()
아래 코멘트에 함께 답변드리겠습니다!

2020-12-23 01:35 UTC, Muntari29 commented on product/views.py
> +
함께 입력되는 경우 ordering만 들어온 경우와 동일한 데이터가 확인됩니다.
개발하고 있는 웹 서비스의 경우 최신/낮은 가격이 함께 적용되는 경우는 없습니다.
최신판매순 -> ordering // 낮은가격순 -> sort 로 구분을 두었습니다.
함께 입력되는 경우를 고려해야할까요?

2020-12-23 02:10 UTC, Muntari29 commented on product/views.py
> +            product_id = int(request.GET.get('product', 1))
path parameter로 구현하였습니다.
우선 하나의 클래스로 id로 접근하는 방법과 search String으로 접근하는것을 모두 구현하였습니다
이같이 2가지를 모두 사용하기 위해서 URL이 아래와 같아지는데 이 방법이 맞는건지 궁금합니다.
10.XXX.XXX.XX:8000/product/1 --> product_id로 찾기
10.XXX.XXX.XX:8000/product/1?search='str' --> product_name으로 찾기
위와 같이 urls.py를 <int:product_id>로 수정하여 반드시 숫자를 입력한 후 쿼리스트링을 시작해야합니다.
의견 부탁드립니다.

2020-12-23 02:41 UTC, lordmyshepherd commented on image 복사본.csv
> -상품명, 가격, 이미지, 카테고리
한번 올라온 파일은 이후에 gitignore에 추가해도 그대로 남아 있습니다!
우선 한번 올라온 csv 파일을 local에서 지우거나 다른 폴더로 이동시킨 후에 commit을 만들어서 push해 주시면 될 것 같습니다.

2020-12-23 02:51 UTC, lordmyshepherd commented on product/views.py
> +            products = Product.objects.all().order_by('-id')
```suggestion
        products = Product.objects.all()
        if price:
            products = products.order_by('price')
        if ordering:
            products = products.order_by('-id')
            
```

2020-12-23 02:51 UTC, lordmyshepherd commented on product/views.py
> +        print(products)
프린트문은 지워주세요!

2020-12-23 02:51 UTC, lordmyshepherd commented on product/views.py
> +            products = Product.objects.all().order_by('-id')
첫번째 line에서 if문을 사용하지 않아도 될 것 같습니다.

2020-12-23 02:51 UTC, lordmyshepherd commented on product/views.py
> +
만약 서비스가 확장되서 경영지원팀이 필요한 관리자 페이지를 만들었을때, 최신판매순이면서 낮은 가격순으로 검색하고 싶다면 새로 뷰를 만드실건가요?

2020-12-23 02:54 UTC, lordmyshepherd requested changes

2020-12-23 02:54 UTC, lordmyshepherd commented on product/views.py
>  class ProductDetailView(View):
상품 상세 페이지에서 이름으로 검색하는 기능이 필요한가요?
상품의 이름으로 해당 상품을 검색하는 기능은 `상품 리스트 뷰`에 기능이 있어야 합니다.

2020-12-23 03:02 UTC, Muntari29 commented on product/views.py
> +            products = Product.objects.all().order_by('-id')
수정하겠습니다.

2020-12-23 03:02 UTC, Muntari29 commented on product/views.py
> +        print(products)
수정하겠습니다!

2020-12-23 06:10 UTC, Muntari29 commented on product/views.py
>  class ProductDetailView(View):
수정하겠습니다.

2020-12-23 07:15 UTC, Muntari29 commented on product/views.py
> +
Product.objects.order_by('price', '-id')로 구성하였습니다.
확인 부탁드립니다. (위 코드는 사실 '-id'만 적용한 결과값과 같습니다.)
의견 부탁드립니다.

2020-12-23 10:23 UTC, lordmyshepherd approved these changes

2020-12-23 10:23 UTC, lordmyshepherd commented on product/views.py
> +        Best_product = [{
```suggestion
        best_product = [{
```

2020-12-23 10:39 UTC, Muntari29 commented on product/views.py
> +        Best_product = [{
수정하겠습니다!

2020-12-23 13:47 UTC, Muntari29 commented on product/views.py
> +
최순등록순이면서 낮은가격순은 삭제하였습니다.

2020-12-23 14:38 UTC, lordmyshepherd approved these changes

2020-12-23 14:38 UTC, lordmyshepherd commented on product/views.py
> +                    'rate_average'    : product.review_set.filter().aggregate(Avg('rate')),
filter()를 붙여준 이유가 있나요??
나중에 수정해주세요~

2020-12-23 14:39 UTC, lordmyshepherd commented
LGTM 👍

2020-12-23 14:39 UTC, merged

2020-12-24 03:38 UTC, Muntari29 commented on product/views.py
> +                    'rate_average'    : product.review_set.filter().aggregate(Avg('rate')),
all() / filter() 가 동일하게 작용하는 부분으로 all을 생략할지 filter로 대체할지 고민하다 filter()로 표기해주었습니다. all()로 변경을해야할까요? 아니면 생략을 해야하나요?